#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                               100
#define IDD_TOOLSPANEL                          102
#define IDD_LEVELGRID                           104
#define IDD_PROPS                               107
#define IDD_DIALOG1                             108
#define IDD_PREVIEW                             110
#define IDD_NEWLEVEL                            112
#define IDD_MOVEREDIT                           114
#define IDC_BUCKETFILL                          1001
#define IDC_LVLWIDTH                            1001
#define IDC_MOVERDIR                            1001
#define IDC_PREVPLAY                            1001
#define IDC_SYNC                                1002
#define IDM_NEW___1                             40000
#define IDM_OPEN___1                            40001
#define IDM_SAVE1                               40002
#define IDM_SAVE_AS___1                         40003
#define IDC_TOOLTABS                            40004
#define IDM_QUIT1                               40004
#define IDM_TOGGLE_GRID1                        40005
#define IDM_UNDO1                               40006
#define IDM_SMALL_GRID1                         40007
#define IDM_MEDIUM_GRID1                        40008
#define IDC_LIST                                40009
#define IDM_LARGE_GRID1                         40009
#define IDM_REDO1                               40010
#define IDC_DRAWLEVELTILE                       40011
#define IDM_CUT1                                40011
#define IDC_DRAWNOOVERRIDE                      40012
#define IDM_COPY1                               40012
#define IDC_ERASELEVELTILE                      40013
#define IDM_PASTE1                              40013
#define IDM_DELETE1                             40014
#define IDC_PLACEPROP                           40015
#define IDM_DESELECT_ALL1                       40015
#define IDM_DON_T_SNAP1                         40016
#define IDC_SELMOVE                             40017
#define IDM_PROPERTIES1                         40017
#define IDC_HORLINE                             40018
#define IDM_DUPLICATE1                          40018
#define IDC_VERLINE                             40020
#define IDC_PREVSTOP                            40021
#define IDC_LVLHEIGHT                           40022
#define IDC_LVLTILESETCOMB                      40024
#define IDC_SPEED                               40025
#define IDC_WIDTH                               40027
#define IDC_PAUSE                               40029
