#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             100
#define IDR_MENU1                               101
#define IDD_ADDWALKER                           103
#define IDD_ADDMOVER                            105
#define IDD_ADDEST                              107
#define IDD_ADDDEFAULT                          109
#define IDD_ADDFLYER                            111
#define IDC_Flight                              1000
#define IDC_ANIMLIST                            1001
#define IDC_CHKDORMANT                          1001
#define IDC_REMOVELEVELTILE                     1002
#define IDC_DESTRUCTYPE                         1003
#define IDC_HAZLIST                             1003
#define IDC_ADDHAZ                              1004
#define IDC_NAME                                1004
#define IDC_DECOLIST                            1005
#define IDC_ADDTILE                             1006
#define IDC_DYNAMICCOMBO                        1007
#define IDC_ADDPROJ                             1009
#define IDC_ISWALL                              1010
#define IDM_NEW1                                40000
#define IDM_OPEN1                               40001
#define IDM_SAVE1                               40002
#define IDM_EXIT1                               40003
#define IDC_COLLIST                             40005
#define IDC_IMAGECOMBO                          40007
#define IDC_NFRAMES                             40011
#define IDC_SPEED                               40013
#define IDC_DYNLIST                             40016
#define IDC_REMOVEDYNAMIC                       40018
#define IDC_ADDDYNAMIC                          40019
#define IDC_ANIMADD                             40023
#define IDC_REMOVEANIM                          40025
#define IDC_PREVIEW                             40026
#define IDC_REMHAZ                              40030
#define IDC_HAZSCALE                            40032
#define IDC_HAZDMG                              40034
#define IDC_DECOADD                             40036
#define IDC_DECOREMOVE                          40038
#define IDC_DECOSCALE                           40040
#define IDC_SCALE                               40041
#define IDC_JUMPSTR                             40048
#define IDC_BASICANIM                           40057
#define IDC_SHOTTYPE                            40061
#define IDC_SHOTDIR                             40063
#define IDC_EDITDYNAMIC                         40065
#define IDC_HP                                  40065
#define IDC_ATTACKANIM                          40066
#define IDC_DEATHANIM                           40067
#define IDC_BASESPRITE                          40071
#define IDC_MOVEANIM                            40072
#define IDC_HAZCHECK                            40074
#define IDC_AGRO                                40075
#define IDC_CDLEFT                              40080
#define IDC_CDRIGHT                             40081
#define IDC_CDTOP                               40082
#define IDC_CDBOTTOM                            40083
#define IDC_REMOVEPROJ                          40085
#define IDC_PROJSCALE                           40087
#define IDC_PROJECTILELIST                      40088
#define IDC_NSHOTS                              40091
#define IDC_DESTID                              40092
#define IDC_ISCEILING                           40092
#define IDC_SHOTDELAY                           40092
